# orbs:
#   docker: circleci/docker@1.5.0
# version: 2.1
# executors:
#   docker-publisher: 
#   environment:
#   IMAGE_NAME: michealgabriel/simple_node
#   docker: # Each job requires specifying an executor
#   # (either docker, macos, or machine), see
#   — image: circleci/node:latest
#   auth:
#   username: $DOCKERHUB_USERNAME
#   password: $DOCKERHUB_PASSWORD
# jobs:
#   publishLatestToHub: 
#   executor: docker-publisher

#   steps: 
#     — checkout
#     — setup_remote_docker
#   — run: 
#   name: Publish Docker Image to Docker Hub
#   command: |
#     echo “$DOCKERHUB_PASSWORD” | docker login -u “$DOCKERHUB_USERNAME” — password-stdin
#     docker build -t simple_node .
#     docker push simple_node:circleci
# workflows:
#   version: 2
#   build-master:
#   jobs:
#     — publishLatestToHub


version: 2  # Version of CircleCI
jobs:
  build:
    docker:
      - image: node:16
    steps:
      - checkout

			# Creates a remote Docker environment configured to execute Docker commands.
      - setup_remote_docker 
       
      - run:
        # installs a docker client that will be used to run the docker commands
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
         # Builds a docker image to push to Docker Hub
				 # Tag (-t) pattern is below, where CircleCI 
				 # to get the Dockerfile from the current directory.
         # <docker_hub_username/docker-hub-password:version>.
          name: Build Docker image
          command: docker build -t michealgabriel/simple_node:v1 .

      - run:
        # Pushes the Docker image you created to the Docker Hub.
        # Replace khabdrick/circleci-tutorial:v1 with the 
				# <docker_hub_username/docker-hub-password:version> you used to build the image above
          name: Push to Docker Hub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push michealgabriel/simple_node:v1